### ISSUE TITLE
Add support for Z-water

### ISSUE THREAD

**Issue by edorf83** [TedTolboom/no.ThermoFloor#2]
When can I use Z-Water in Homey?  I have alredy bougth this device, but I cant use it yet..

**Comment by MbenzNo** [comment]
Hi! any plans for adding other HeatIt/Thermo floor devices to this app? Would like to have support for the 25A relay switch : https://www.tronika.no/no/index.php?controller=attachment&id_attachment=682

**Comment by TedTolboom** [comment]
See my comment at the forum:
https://community.athom.com/t/thermofloor-multireg-heat-it-app-v1-0-0/166/15

**Comment by TedTolboom** [comment]
@edorf83 @MbenzNo Brief update on the Z-water and Z-relay.
I just released the v2.1.0 update that includes the Z-TRM2(fx) support to the app store.

Pending feedback on that release, I will start working on implementing the Z-relay and Z-water devices.

**Comment by TedTolboom** [comment]
Initial support for the Z-water is added in v2.1.1 (BETA)

Temperature readout is still not possible due to a bug in the Z-wave core.
All 10 relays can be controlled.
