### ISSUE TITLE
Heatit ztrm2

### ISSUE THREAD

**Issue by follox** [TedTolboom/no.ThermoFloor#20]
I have the old version of Heatit called ztrm2. This thermostat was replaced with the ztrm2fx, but I can't change to this as it does not have a sensor for air.

Any possibilites to get this to work with Homey? I tried the ztrm2fx template, but this does not work correctly. The command class is different on ztrm2 than ztrm2fx.

**Comment by TedTolboom** [comment]
@follox is this question still actual or have you replaced the Z-TRM2 for the Z-TRM2fx?

**Comment by follox** [comment]
Hi Ted,

No, I did change to Heatit ztrm2fx.
We have spoke together at Slack 😀

Best Regards
Øyvind Tukun

søn. 15. sep. 2019, 20:41 skrev Ted Tolboom <notifications@github.com>:
