### ISSUE TITLE
Z-relay not reading Temp sensor 10k ntc 

### ISSUE THREAD

**Issue by kjetilknutsen73** [TedTolboom/no.ThermoFloor#21]
Hi 
Have tried 3 different 10k NTC Temp scensor but i dont get any Temp reading ..

Settings = 10k Ntc

**Comment by TedTolboom** [comment]
@kjetilknutsen73 v2.3.0-BETA has been uploaded to the Homey Apps store to the BETA branch of the Heatit app, awaiting Athom's approval. Could you try to remove the Z-Relay and re-include it based on this version.
This update should resolve stability issues that could prevent temperature readings to be processed

**Comment by kjetilknutsen73** [comment]
Works GREAT !!!!!!!!!!!!!!!!!!!!!!!!!

Thx


Kjetil Knutsen
Leder IT-støtte

+47 51 87 50 54
+47 901 04 505

Prof. Olav Hanssensvei 15, 4021 Stavanger, Norway

[cid:norce_426cc920-64ab-4893-95d0-c29d5dab670c.png]

NORCE Norwegian Research Centre AS
norceresearch.no<https://www.norceresearch.no/>

**Comment by TedTolboom** [comment]
Thanks for the feedback. I'll close the issue then.

**Comment by kjetilknutsen73** [comment]
Hi

Just one thing.

Dies not display voltage

[cid:5F253A82-3A40-4B48-A083-51E01A13B418]

Mvh
Kjetil Knutsen


Kjetil Knutsen
Leder IT-støtte

+47 51 87 50 54
+47 901 04 505

Prof. Olav Hanssensvei 15, 4021 Stavanger, Norway

[cid:norce_426cc920-64ab-4893-95d0-c29d5dab670c.png]

NORCE Norwegian Research Centre AS
norceresearch.no<https://www.norceresearch.no/>

________________________________
Fra: Ted Tolboom <notifications@github.com>
Sendt: Friday, October 11, 2019 8:39:30 PM
Til: TedTolboom/no.ThermoFloor <no.ThermoFloor@noreply.github.com>
Kopi: Kjetil Knutsen <kjkn@norceresearch.no>; Mention <mention@noreply.github.com>
Emne: Re: [TedTolboom/no.ThermoFloor] Z-relay not reading Temp sensor 10k ntc (#21)


Thanks for the feedback. I'll close the issue then.
