### ISSUE TITLE
No temperature data z-water

### ISSUE THREAD

**Issue by 2tracer** [TedTolboom/no.ThermoFloor#34]
Hello.
I do not get any sensor to show temperature in the z-water (relay 1) on the Homey.
I have connected 4 10k ntc sensors.
Do you know how to fix this?

Best regards
Karl

**Comment by 2tracer** [comment]
![EE29BB58-31B0-4336-9823-81278747824F](https://user-images.githubusercontent.com/56477080/73208195-4e931680-4146-11ea-86a1-e74072e29f90.png)

**Comment by 2tracer** [comment]
I asked heatit on facebook messenger and the answered me this:
You must put assosiations from endpoint 0 (group 1) to gateway with multichannel encapsulation.

Do you know what they mean? 😇😇

**Comment by TedTolboom** [comment]
They are originally set in this way during the inclusion process; is it possible to send me the diagnostics report and a screenshot of the advanced settings (association groups)?

**Comment by 2tracer** [comment]
Hello.
Yes offcorse. :-)

I named the report, Report missing sesor data:
61fdeadc-391a-4f6d-ad5c-0327ade26d13

[image1.png]

[image2.png]

[image3.png]


Best regards

Karl

Sendt fra min iPhone

27. jan. 2020 kl. 21:59 skrev Ted Tolboom <notifications@github.com<mailto:notifications@github.com>>:


They are originally set in this way during the inclusion process; is it possible to send me the diagnostics report and a screenshot of the advanced settings (association groups)?

**Comment by 2tracer** [comment]
![1CED93A3-6AFB-4D3C-AFB3-5D3C60BE1C32](https://user-images.githubusercontent.com/56477080/73224384-9d05dc80-4169-11ea-9ba1-01089dd047da.png)
![B7AEC25B-2A06-4DC1-91A6-6C06554774E8](https://user-images.githubusercontent.com/56477080/73224385-9d05dc80-4169-11ea-8fbf-645003d32b41.png)
![8482F148-5BD1-4815-9E31-C65A9D3A1F67](https://user-images.githubusercontent.com/56477080/73224386-9d05dc80-4169-11ea-9610-bf1b9ba31cf6.png)

**Comment by 2tracer** [comment]
Did i do it rigth? :-)

**Comment by 2tracer** [comment]
Hey Ted. Did you get what you need? Best regards

**Comment by 2tracer** [comment]
Hello.
I fikses this by changing the paramerer on assosiation. Now it works good. 👍👍

![69C7C72B-34F0-4CFD-8B50-521BE31E4696](https://user-images.githubusercontent.com/56477080/74006699-c6e6ac80-497c-11ea-84b2-a7cef077dc94.png)

**Comment by TedTolboom** [comment]
Thanks for the feedback!
