### ISSUE TITLE
No Heatit Z-TRM3 support

### ISSUE THREAD

**Issue by sverrebm** [TedTolboom/no.ThermoFloor#40]
This app really should have support for Heatits most recent floor thermostat, Z-TRM3.

**Comment by TedTolboom** [comment]
@sverrebm I have received the Z-TRM3 finally and will spend time this week to add support for it.

**Comment by TedTolboom** [comment]
@sverrebm version 2.5.0 will provide support for the Z-TRM3.
I've just uploaded that version to the app store for approval, pending this approval, you can install the update through this link: https://homey.app/a/no.thermofloor/test/

I'll close the issue for now, since resolved
