### ISSUE TITLE
Heatit zwave thermostat gen1 problem

### ISSUE THREAD

**Issue by Stave94** [TedTolboom/no.ThermoFloor#43]
After the latest update i have lost contact with my Heatit zwave thermostat gen1.

**Comment by Stave94** [comment]
And my Z-push button 8

**Comment by TedTolboom** [comment]
@stave94 can you describe the problem you experience?
In the last updates, no changes have been made to these two devices.

**Comment by TedTolboom** [comment]
I don’t see any images; responding by mail and attaching files doesn’t work; you’ll need to upload to the website.

Can you try to pull the plug of Homey; leave disconnected for 10 minutes and the reconnect?

**Comment by Stave94** [comment]
Aah, ok!  but it looks like puling the plug on homey did the trick :) Thank
you!

fre. 5. jun. 2020, 22:29 skrev Ted Tolboom <notifications@github.com>:

**Comment by TedTolboom** [comment]
Fix by restart
