### ISSUE TITLE
Z-TRM3 not reporting power consumption 

### ISSUE THREAD

**Issue by danaksel** [TedTolboom/no.ThermoFloor#48]
Hi!
I’ve just realized that my Z-TRM3 isn’t reporting the right power consumption. Mine has reported 14 watts 24/7 for since installed several weeks ago. My friend has the exact same issue. Something that can be looked into?

**Comment by vsurlien** [comment]
Same problem here. Mine rapported correct Watt once, and then steady at 0.14W. kWh is and temp are working.

**Comment by vsurlien** [comment]
I tried changing association group as described here. This worked for me. 
https://community.athom.com/t/heatit-z-wave-app-v2-7-0/166/333

**Comment by TedTolboom** [comment]
Are all issues occuring on Homey v4.2 or on Homey v5.0?

**Comment by vsurlien** [comment]
My is 4.2

**Comment by danaksel** [comment]
Mine is 4.2 as well.

**Comment by TedTolboom** [comment]
I'm currently looking into the issue and are in contact with Heatit to clarify

**Comment by TedTolboom** [comment]
I've just released the 2.7.1 update of the app, that should resolve a bug at Athom's side while setting the correct association groups, which resulted in that the Z-TRM3 thermostat did not have the right communication paths toward Homey.

After updating of the the app, the device should migrate to the right association groups automatically and should start reporting as expected.

I'll close this issue for now, assuming resolved. Please re-open when not.
