### ISSUE TITLE
Z-TRM3

### ISSUE THREAD

**Issue by lurajon** [TedTolboom/no.ThermoFloor#49]
Thank you for your awesome work with this app.

I bought the TRM3 a couple of months ago (before the app had support for TRM3).

I have a problem with the thermostat where it continues to heat even though the target temp is reached. 

I also see that temperature thermostat is "internal" (not sure if this is a fixed value) even though I have configured to use the floor sensor on the device.

Best regards,

Jone

**Comment by lurajon** [comment]
<img width="1500" alt="Screenshot 2020-07-31 at 11 43 47" src="https://user-images.githubusercontent.com/1674209/89023530-04bd0000-d324-11ea-9009-5872fd0806d6.png">

**Comment by TedTolboom** [comment]
> I have a problem with the thermostat where it continues to heat even though the target temp is reached.
Typical the Z-TRM3 is controlling the heating system independently, based on the set temperatures and thermostat mode.
Are you sure that you setup the thermostat correctly; specifically regarding the modus?

**Comment by TedTolboom** [comment]
I've just released the 2.7.1 update of the app, that should resolve a bug at Athom's side while setting the correct association groups, which resulted in that the Z-TRM3 thermostat did not have the right communication paths toward Homey.

After updating of the the app, the device should migrate to the right association groups automatically and should start reporting as expected.

I'll close this issue for now, assuming resolved. Please re-open when not.
