### ISSUE TITLE
Trm 3 floorsensor

### ISSUE THREAD

**Issue by robkeemink** [TedTolboom/no.ThermoFloor#50]
no temp floor in app

**Comment by TedTolboom** [comment]
Can you please provide more information?

**Comment by TedTolboom** [comment]
I've just released the 2.7.1 update of the app, that should resolve a bug at Athom's side while setting the correct association groups, which resulted in that the Z-TRM3 thermostat did not have the right communication paths toward Homey.

After updating of the the app, the device should migrate to the right association groups automatically and should start reporting as expected.

I'll close this issue for now, assuming resolved. Please re-open when not.
