### ISSUE TITLE
Trouble connecting heatit trm3 to my homey hub

### ISSUE THREAD

**Issue by asbfin** [TedTolboom/no.ThermoFloor#55]
When trying to connect my heatit trm3 to homey hub, it stops in step 2 - and ECL is displayet at trm3. Then I have to abort the installation in the homey app, and the item is not installered. How to troubleshoot?

**Comment by TedTolboom** [comment]
Z-wave has a two step inclusion process; first Excluding it, then Including the thermostat.
Please follow the instructions provided.
If Ecl is shown, the first step is completed successfully. 
Next step is Inclusion, press the device button again to set the thermostat in inclusion mode.

**Comment by asbfin** [comment]
Thx - that sorted out my issues!

Regards, 
Asbjørn

**Comment by TedTolboom** [comment]
Great, closing issue
